In [ ]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## Creating numpy arrays
    1. From python lists/tuples
    2. using functions returning numpy arrays
    3. reading data from files 

#### From Lists:

In [ ]:
# create a simple array - not in matrix format
v = np.array([1,2,3])
print "Array : ", v.shape, v

# create a row vector
v = np.array([[1,2,3]])
print "Row Vector: ", v.shape, v

# create a column vector
v = np.array([[1],[2],[3]])
print 'Column Vector: ', v.shape, v

# create a matrix
v = np.array([[1,2], [3,4]])
print 'Matrix: ', v.shape
print v

# get #elements in an array
print "#elements in %s matrix: %d" %(v.shape, v.size)

#### Using Array generating functions

In [ ]:
# create a range of values
# 'arange' generates equally spaced values with incr/decr (stop-start)/step
a1 = np.arange(0, 10, 1)    # start, stop step
print a1

# range in reverse order
a2 = np.arange(10, 0, -1)
print a2

In [ ]:
# 'linspace' similar to 'arange', but instead of set, num_of_samples need to be specified
l1 = np.linspace(0, 10, num=10, endpoint=False, dtype=np.int32)
print 'l1: ', l1

l2 = np.linspace(0, 1, num=5)
print 'l2: ', l2

In [ ]:
# 'logspace' numbers evenly spaces on log scales, between 'start' and 'stop' values
log_sample1 = np.logspace(0, 1, num=10, base=10)
print 'log_sample1: ', log_sample1
log_sample2 = np.logspace(0, 1, num=10, base=np.e)
print 'log_sample2: ', log_sample2

#### Random data

In [ ]:
# seed random number generator
np.random.seed(1234)

# uniform random sample in half interval [0, 1)
uniform_sample1 = np.random.random_sample(4)  # size param specifes dimension
print 'uniform_sample1 of size %s: %s' %(uniform_sample1.shape, uniform_sample1)
uniform_sample2 = np.random.random_sample((2,2))
print 'uniform_sample2 of size %s: %s\n' %(uniform_sample2.shape, uniform_sample2)

# np.random.random() is an alias for np.random.random_sample()
random_sample1 = np.random.random(4)
print 'random_sample1 of size %s is %s\n' %(random_sample1.shape, random_sample1)

# sample random integers in a range
# draw 4 samples from integer range [0, 10)
int_sample1 = np.random.randint(0, 10, 4)
print 'int_sample1 of size %s is %s' %(int_sample1.shape, int_sample1)
int_sample2 = np.random.randint(0, 10, (3,3))
print 'int_sample2 of size %s is %s\n' %(int_sample2.shape, int_sample2)

# array permutation
orig_vector = np.arange(5)
permuted_vector = np.random.permutation(orig_vector)
print 'orig vector ', orig_vector
print 'permuted vector ', permuted_vector
# In matrix permutation, only elements along first index are shuffled
orig_matrix = np.random.randint(0, 20, (3,3))
permuted_matrix = np.random.permutation(orig_matrix)
print 'orig matrix ', orig_matrix
print 'permuted matrix %s\n' %(permuted_matrix,)

# sample from a discrete set of symbols with/without replacement subject to uniform/non-uniform probability
cities = ('HYD', 'BLR', 'MUM', 'DEL')
choice_distr1 = np.random.choice(cities, 4, replace=False)
print 'choice_distr1 : ', choice_distr1
choice_distr2 = np.random.choice(cities, 4, replace=True, p=(.4, .1, .1, .4))
print 'choice_distr2 : ', choice_distr2
print '\n'

# np.random also has sampling routines for 
# beta, binomial, chisquare, exponential, f, gamma,}

##### np.random also has sampling routines for following distributions
* beta, binomial, chisquare, exponential, f, gamma, geometric, hypergeometric, laplace, logistic, lognormal, negative binomial, normal, poisson, uniform, weibull
* dirichlet, multinomial, multivariate normal
* standrd distributions: cauchy, exponential, gamma, normal, t 

##### np.diag()
* to create a diagonal matrix
* to access any diagonal of a matrix

In [83]:
# creating diagonal matrices
diagonal_matrix1 = np.diag((1,2,3), k=0) # diagonal entries, diagonal index (0 - main diagonal)
print "diagonal_matrix1 : ", diagonal_matrix1
diagonal_matrix2 = np.diag([1,2,3], k=1)
print "diagonal_matrix2: ", diagonal_matrix2
print '\n'

# extract diagonals from a matrix
matrix1 = np.arange(16).reshape(4,4)
print "matrix1: ", matrix1
print "main diagonal: ", np.diag(matrix1, k=0)
print "diagonal with offest 1: ", np.diag(matrix1, k=1)
print "diagonal with offest -1: ", np.diag(matrix1, k=-1)

diagonal_matrix1 :  [[1 0 0]
 [0 2 0]
 [0 0 3]]
diagonal_matrix2:  [[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


matrix1:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
main diagonal:  [ 0  5 10 15]
diagonal with offest 1:  [ 1  6 11]
diagonal with offest -1:  [ 4  9 14]


##### np.zeros()   np.ones()
* to create 0 matrices and 1 matrices

In [85]:
# zero matrix
zero_matrix = np.zeros((3,4), dtype=np.int32)
print "zero_matrix of shape %s is %s " %(zero_matrix.shape, zero_matrix)
# one matrix
one_matrix = np.ones((2,2), dtype=np.int32)
print 'one_matrix of shape %s is %s ' %(one_matrix.shape, one_matrix)

zero_matrix of shape (3, 4) is [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 
one_matrix of shape (2, 2) is [[1 1]
 [1 1]] 


#### Reading data from files

In [86]:
!head ../stockholm_td_adj.dat

1800  1  1    -6.1    -6.1    -6.1 1
1800  1  2   -15.4   -15.4   -15.4 1
1800  1  3   -15.0   -15.0   -15.0 1
1800  1  4   -19.3   -19.3   -19.3 1
1800  1  5   -16.8   -16.8   -16.8 1
1800  1  6   -11.4   -11.4   -11.4 1
1800  1  7    -7.6    -7.6    -7.6 1
1800  1  8    -7.1    -7.1    -7.1 1
1800  1  9   -10.1   -10.1   -10.1 1
1800  1 10    -9.5    -9.5    -9.5 1


In [87]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %install_default_config  %install_ext  %install_profiles  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%latex  %%

In [90]:
%colors

UsageError: %colors: you must specify a color scheme. See '%colors?'